version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
      - dependency-name: "com.sun.xml.ws:jaxws-tools"
      - dependency-name: "org.apache.cxf:cxf-rt-frontend-jaxws"
      - dependency-name: "org.apache.cxf:cxf-rt-features-logging"
      - dependency-name: "org.apache.cxf:cxf-rt-transports-http"
      - dependency-name: "org.apache.cxf:cxf-rt-ws-security"
      - dependency-name: "org.apache.ws.xmlschema:xmlschema-core"
      - dependency-name: "no.nav.tjenestespesifikasjoner:altinn-correspondence-agency-external-basic"
      - dependency-name: "org.apache.kafka:kafka_2.12"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.kafka:kafka-streams"
        update-types: ["version-update:semver-major"]  
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
