version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    1ignore:
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.sun.xml.ws:jaxws-tools"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.cxf:cxf-rt-frontend-jaxws"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.cxf:cxf-rt-features-logging"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.cxf:cxf-rt-transports-http"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.cxf:cxf-rt-ws-security"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.ws.xmlschema:xmlschema-core"
        update-types: ["version-update:semver-major"]
              
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
