apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmaltinn
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosmaltinn
        mountPath: /secrets/serviceuser
      - kvPath: azuread/data/dev/creds/syfosmaltinn
        mountPath: /secrets/azuread
  ingresses:
    - "https://syfosmaltinn.nais.preprod.local"
  webproxy: true
  env:
    - name: PDL_BASE_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: AAD_ACCESS_TOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: NARMESTELEDER_CLIENT_ID
      value: a7e7ad0e-4e17-4f19-8aa6-39d73e62fff8
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
