apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmaltinn
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: www.altinn.no
        - host: api-gw.oera.no
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        diskSize: 10
        diskAutoresize: true
        databases:
          - name: syfosmaltinn
            envVarPrefix: NAIS_DATABASE

  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 60
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  vault:
    enabled: false
  filesFrom:
    - secret: syfosmaltinn-secrets
  envFrom:
    - secret: syfosmaltinn-api-keys
  ingresses:
    - "https://syfosmaltinn.intern.nav.no"
  webproxy: true
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: ALTINN_URL
      value: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
    - name: JURIDISKLOGG_REST_URL
      value: https://api-gw.oera.no/sykmelding-fss-proxy/juridisklogg/juridisklogg/api/rest/logg
    - name: KAFKA_CLIENT_ID
      value: syfosmaltinn
