apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmaltinn
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosmaltinn
        mountPath: /secrets/serviceuser
      - kvPath: azuread/data/prod/creds/syfosmaltinn
        mountPath: /secrets/azuread
      - kvPath: /kv/prod/fss/syfosmaltinn/teamsykmelding
        mountPath: /secrets/vault
  ingresses:
    - "https://syfosmaltinn.nais.adeo.no"
  webproxy: true
  env:
    - name: PDL_BASE_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: AAD_ACCESS_TOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: NARMESTELEDER_CLIENT_ID
      value: ccf8c36f-27e6-4e76-8250-9a49939df7ef
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: EKSTERN_ALTINN_BEHANDLEALTINNMELDING_V1_ENDPOINTURL
      value: https://pep-gw.oera.no:9443/ekstern/altinn/BehandleAltinnMelding/v1
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
