apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmaltinn
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: tt02.altinn.no
        - host: api-gw-q1.oera.no
  gcp:
    sqlInstances:
      - name: syfosmaltinn-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: syfosmaltinn
            envVarPrefix: NAIS_DATABASE

  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  vault:
    enabled: false
  filesFrom:
    - secret: syfosmaltinn-secrets
  envFrom:
    - secret: syfosmaltinn-api-keys
  ingresses:
    - "https://syfosmaltinn.dev.nav.no"
  webproxy: true
  env:
    - name: PDL_BASE_PATH
      value: https://api-gw-q1.oera.no/pdl-api/graphql
    - name: AAD_ACCESS_TOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: NARMESTELEDER_SCOPE
      value: api://dev-gcp.teamsykmelding.narmesteleder/.default
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SECURITYTOKENSERVICE_URL
      value: https://api-gw-q1.oera.no/security-token-service/rest/v1/sts/token
    - name: ALTINN_URL
      value: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
    - name: ALTINN_PORTAL_BASEURL
      value: https://tt02.altinn.no
    - name: JURIDISKLOGG_REST_URL
      value: https://api-gw-q1.oera.no/sykmelding-fss-proxy/juridisklogg/juridisklogg/api/rest/logg
    - name: KAFKA_CLIENT_ID
      value: syfosmaltinn
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.dev.nav.no
